import { getDb } from "../api/queries/connection";
import { books } from "./schema";

const sampleBooks = [
  {
    title: "The Midnight Garden",
    author: "Elena Blackwood",
    description: "In a garden that only blooms at midnight, secrets of the past intertwine with the present. A hauntingly beautiful tale of love, loss, and redemption that will stay with you long after the last page. This magical realism novel weaves together mystery and romance in an unforgettable setting.",
    category: "fiction" as const,
    price: "18.99",
    stock: 45,
    coverImage: "/book-covers/book1.jpg",
    isbn: "978-0-123456-78-1",
    publisher: "Moonlight Press",
    publishedYear: 2024,
    pages: 342,
    isFeatured: true,
    isBestseller: true,
    rating: "4.5",
    reviewCount: 128,
  },
  {
    title: "Echoes of Tomorrow",
    author: "Marcus Chen",
    description: "A gripping science fiction novel set in a world where memories can be traded like currency. When a memory dealer discovers a conspiracy that threatens to erase humanity's collective past, he must race against time to save what makes us human.",
    category: "fiction" as const,
    price: "22.99",
    stock: 30,
    coverImage: "/book-covers/book2.jpg",
    isbn: "978-0-123456-78-2",
    publisher: "Future Horizons",
    publishedYear: 2024,
    pages: 416,
    isFeatured: true,
    isBestseller: true,
    rating: "4.7",
    reviewCount: 95,
  },
  {
    title: "The Last Letter",
    author: "Sarah Whitfield",
    description: "An epistolary masterpiece that unfolds through a series of discovered letters spanning three generations. Each letter reveals a piece of a family's hidden history, leading to a revelation that changes everything they thought they knew about love and sacrifice.",
    category: "fiction" as const,
    price: "16.99",
    stock: 55,
    coverImage: "/book-covers/book3.jpg",
    isbn: "978-0-123456-78-3",
    publisher: "Heritage Books",
    publishedYear: 2023,
    pages: 298,
    isFeatured: false,
    isBestseller: true,
    rating: "4.3",
    reviewCount: 210,
  },
  {
    title: "Thinking Clearly",
    author: "Dr. James Morton",
    description: "A groundbreaking exploration of cognitive biases and decision-making. Dr. Morton distills decades of research into practical strategies for clearer thinking, better judgment, and smarter choices in every aspect of life.",
    category: "non-fiction" as const,
    price: "24.99",
    stock: 60,
    coverImage: "/book-covers/book4.jpg",
    isbn: "978-0-123456-78-4",
    publisher: "MindWorks Publishing",
    publishedYear: 2024,
    pages: 384,
    isFeatured: true,
    isBestseller: false,
    rating: "4.6",
    reviewCount: 87,
  },
  {
    title: "The Art of Rest",
    author: "Claudia Rivers",
    description: "In our hyper-connected world, rest has become a radical act. Claudia Rivers examines the science of relaxation across cultures, from the Japanese art of forest bathing to the Nordic concept of hygge, offering a transformative guide to reclaiming peace.",
    category: "non-fiction" as const,
    price: "19.99",
    stock: 40,
    coverImage: "/book-covers/book5.jpg",
    isbn: "978-0-123456-78-5",
    publisher: "Serene Press",
    publishedYear: 2024,
    pages: 256,
    isFeatured: false,
    isBestseller: true,
    rating: "4.4",
    reviewCount: 156,
  },
  {
    title: "Quantum Worlds",
    author: "Prof. Alan Sterling",
    description: "Journey into the mind-bending realm of quantum physics without the complex mathematics. Professor Sterling makes the impossible concepts of superposition, entanglement, and quantum computing accessible and thrilling for every reader.",
    category: "science" as const,
    price: "26.99",
    stock: 25,
    coverImage: "/book-covers/book6.jpg",
    isbn: "978-0-123456-78-6",
    publisher: "Discovery Books",
    publishedYear: 2024,
    pages: 320,
    isFeatured: true,
    isBestseller: true,
    rating: "4.8",
    reviewCount: 73,
  },
  {
    title: "The Nature Code",
    author: "Dr. Lisa Yamamoto",
    description: "From the spirals of a seashell to the branching of trees, nature follows hidden mathematical patterns. Dr. Yamamoto reveals the elegant code underlying the natural world, connecting DNA sequences to galaxy formations in a breathtaking synthesis.",
    category: "science" as const,
    price: "21.99",
    stock: 35,
    coverImage: "/book-covers/book7.jpg",
    isbn: "978-0-123456-78-7",
    publisher: "GreenLeaf Science",
    publishedYear: 2023,
    pages: 288,
    isFeatured: false,
    isBestseller: false,
    rating: "4.2",
    reviewCount: 64,
  },
  {
    title: "Empires of Sand",
    author: "Robert Khalil",
    description: "A sweeping historical epic that brings ancient civilizations to life. From the Library of Alexandria to the burning of Persepolis, witness the rise and fall of empires through the eyes of those who lived through history's most pivotal moments.",
    category: "history" as const,
    price: "23.99",
    stock: 38,
    coverImage: "/book-covers/book8.jpg",
    isbn: "978-0-123456-78-8",
    publisher: "Chronicle House",
    publishedYear: 2024,
    pages: 512,
    isFeatured: true,
    isBestseller: true,
    rating: "4.6",
    reviewCount: 142,
  },
  {
    title: "The Silk Roads",
    author: "Amira Hassan",
    description: "An illuminating journey along the ancient trade routes that connected East and West. Amira Hassan weaves together commerce, culture, and conquest in a narrative that reshapes our understanding of how civilizations influenced one another.",
    category: "history" as const,
    price: "20.99",
    stock: 42,
    coverImage: "/book-covers/book9.jpg",
    isbn: "978-0-123456-78-9",
    publisher: "Atlas Publishing",
    publishedYear: 2023,
    pages: 368,
    isFeatured: false,
    isBestseller: false,
    rating: "4.3",
    reviewCount: 98,
  },
  {
    title: "Code & Craft",
    author: "David Park",
    description: "Programming is not just a technical skill—it's a creative craft. David Park explores the artistry behind elegant code, drawing parallels between software development and traditional crafts like woodworking and pottery.",
    category: "technology" as const,
    price: "34.99",
    stock: 50,
    coverImage: "/book-covers/book10.jpg",
    isbn: "978-0-123456-79-0",
    publisher: "TechArt Press",
    publishedYear: 2024,
    pages: 432,
    isFeatured: true,
    isBestseller: true,
    rating: "4.7",
    reviewCount: 189,
  },
  {
    title: "Digital Minds",
    author: "Dr. Rachel Foster",
    description: "Artificial intelligence is reshaping our world at an unprecedented pace. Dr. Foster provides a balanced, insightful look at AI's potential and perils, exploring ethical questions and practical implications for society.",
    category: "technology" as const,
    price: "27.99",
    stock: 28,
    coverImage: "/book-covers/book11.jpg",
    isbn: "978-0-123456-79-1",
    publisher: "Neural Press",
    publishedYear: 2024,
    pages: 352,
    isFeatured: false,
    isBestseller: true,
    rating: "4.5",
    reviewCount: 112,
  },
  {
    title: "The Little Explorer",
    author: "Maya Thompson",
    description: "Join little Leo on an enchanting adventure through enchanted forests and over sparkling seas. A beautifully illustrated children's book that celebrates curiosity, courage, and the joy of discovery.",
    category: "childrens" as const,
    price: "14.99",
    stock: 75,
    coverImage: "/book-covers/book12.jpg",
    isbn: "978-0-123456-79-2",
    publisher: "Wonderland Kids",
    publishedYear: 2024,
    pages: 48,
    isFeatured: true,
    isBestseller: false,
    rating: "4.8",
    reviewCount: 234,
  },
  {
    title: "Starlight Stories",
    author: "Oliver Nightingale",
    description: "A collection of magical bedtime tales where stars come alive, the moon tells secrets, and dreams take flight. Each story is crafted to spark imagination while gently teaching values of kindness and bravery.",
    category: "childrens" as const,
    price: "13.99",
    stock: 65,
    coverImage: "/book-covers/book13.jpg",
    isbn: "978-0-123456-79-3",
    publisher: "Dreamscape Books",
    publishedYear: 2023,
    pages: 64,
    isFeatured: false,
    isBestseller: true,
    rating: "4.9",
    reviewCount: 312,
  },
  {
    title: "The 5 AM Club",
    author: "Robin Sharma",
    description: "Legendary leadership and elite performance expert Robin Sharma introduces a revolutionary morning routine that has helped thousands maximize their potential. Through an enchanting story, discover how rising early can transform every area of your life.",
    category: "self-help" as const,
    price: "19.99",
    stock: 80,
    coverImage: "/book-covers/book14.jpg",
    isbn: "978-0-123456-79-4",
    publisher: "HarperCollins",
    publishedYear: 2018,
    pages: 336,
    isFeatured: true,
    isBestseller: true,
    rating: "4.4",
    reviewCount: 567,
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    description: "A groundbreaking guide to building good habits and breaking bad ones. James Clear draws on biology, psychology, and neuroscience to create an easy-to-understand framework for improving every day. Learn how tiny changes can lead to remarkable results.",
    category: "self-help" as const,
    price: "21.99",
    stock: 100,
    coverImage: "/book-covers/book15.jpg",
    isbn: "978-0-123456-79-5",
    publisher: "Avery",
    publishedYear: 2018,
    pages: 320,
    isFeatured: true,
    isBestseller: true,
    rating: "4.8",
    reviewCount: 892,
  },
  {
    title: "The Silent Witness",
    author: "Arthur Blackwell",
    description: "London, 1890. When a prominent judge is found dead in his chambers, Detective Inspector Evelyn Marsh must navigate a web of secrets, lies, and Victorian intrigue. A masterful historical mystery that keeps you guessing until the final revelation.",
    category: "mystery" as const,
    price: "17.99",
    stock: 33,
    coverImage: "/book-covers/book16.jpg",
    isbn: "978-0-123456-79-6",
    publisher: "Mystery House",
    publishedYear: 2024,
    pages: 384,
    isFeatured: false,
    isBestseller: true,
    rating: "4.5",
    reviewCount: 178,
  },
  {
    title: "Shadow Play",
    author: "Nina Volkov",
    description: "In the rain-soaked streets of a noir metropolis, private investigator Jack Holloway takes on a case that leads him into a labyrinth of shadowy figures and buried secrets. A stylish, atmospheric thriller that pays homage to classic noir.",
    category: "mystery" as const,
    price: "16.99",
    stock: 27,
    coverImage: "/book-covers/book17.jpg",
    isbn: "978-0-123456-79-7",
    publisher: "Noir Press",
    publishedYear: 2023,
    pages: 312,
    isFeatured: false,
    isBestseller: false,
    rating: "4.1",
    reviewCount: 89,
  },
  {
    title: "Realm of Dragons",
    author: "Celestia Dawn",
    description: "In a world where dragons rule the skies and ancient magic stirs beneath the earth, a young blacksmith discovers she is the last descendant of dragonlords. An epic fantasy adventure filled with breathtaking world-building and unforgettable characters.",
    category: "fantasy" as const,
    price: "24.99",
    stock: 48,
    coverImage: "/book-covers/book18.jpg",
    isbn: "978-0-123456-79-8",
    publisher: "Dragonfire Books",
    publishedYear: 2024,
    pages: 528,
    isFeatured: true,
    isBestseller: true,
    rating: "4.7",
    reviewCount: 267,
  },
  {
    title: "The Crystal Throne",
    author: "Elara Moonweaver",
    description: "When the Crystal Throne shatters, seven kingdoms plunge into chaos. Princess Aurelia must embark on a perilous quest to gather the scattered shards before darkness consumes her world. A spellbinding tale of magic, politics, and destiny.",
    category: "fantasy" as const,
    price: "22.99",
    stock: 36,
    coverImage: "/book-covers/book19.jpg",
    isbn: "978-0-123456-79-9",
    publisher: "Fantasy Realms",
    publishedYear: 2024,
    pages: 464,
    isFeatured: false,
    isBestseller: true,
    rating: "4.4",
    reviewCount: 145,
  },
  {
    title: "Love in Paris",
    author: "Camille Beaumont",
    description: "When American artist Claire inherits a small apartment in Montmartre, she discovers an old love letter hidden in the walls. Following its clues through the City of Light, she finds not just the story of a wartime romance, but perhaps her own.",
    category: "romance" as const,
    price: "15.99",
    stock: 52,
    coverImage: "/book-covers/book20.jpg",
    isbn: "978-0-123456-80-0",
    publisher: "Parisian Press",
    publishedYear: 2024,
    pages: 342,
    isFeatured: true,
    isBestseller: false,
    rating: "4.3",
    reviewCount: 198,
  },
  {
    title: "The Coffee Shop Date",
    author: "Emily Hart",
    description: "Two strangers, one cozy coffee shop, and a chance encounter that changes everything. Emily Hart delivers a heartwarming contemporary romance about finding love in the most ordinary places, one cup of coffee at a time.",
    category: "romance" as const,
    price: "14.99",
    stock: 58,
    coverImage: "/book-covers/book21.jpg",
    isbn: "978-0-123456-80-1",
    publisher: "Heartwarming Reads",
    publishedYear: 2023,
    pages: 278,
    isFeatured: false,
    isBestseller: true,
    rating: "4.5",
    reviewCount: 267,
  },
  {
    title: "Against All Odds",
    author: "Michael Torres",
    description: "The remarkable true story of a young immigrant who rose from poverty to become one of the most influential scientists of our time. An inspiring biography that proves determination and curiosity can overcome any obstacle.",
    category: "biography" as const,
    price: "23.99",
    stock: 29,
    coverImage: "/book-covers/book22.jpg",
    isbn: "978-0-123456-80-2",
    publisher: "Life Stories Press",
    publishedYear: 2024,
    pages: 416,
    isFeatured: false,
    isBestseller: false,
    rating: "4.6",
    reviewCount: 76,
  },
  {
    title: "The Examined Life",
    author: "Prof. Sophia Laurent",
    description: "A profound journey through the history of philosophical thought, from Socrates to Simone de Beauvoir. Professor Laurent makes complex ideas accessible, showing how ancient wisdom remains deeply relevant to our modern lives.",
    category: "philosophy" as const,
    price: "20.99",
    stock: 22,
    coverImage: "/book-covers/book23.jpg",
    isbn: "978-0-123456-80-3",
    publisher: "Wisdom Books",
    publishedYear: 2024,
    pages: 368,
    isFeatured: false,
    isBestseller: false,
    rating: "4.2",
    reviewCount: 54,
  },
  {
    title: "Whispers of the Heart",
    author: "Aria Moon",
    description: "A delicate collection of poems that explores love, loss, and the quiet moments that define our lives. Each verse is crafted with precision and passion, inviting readers to find their own reflections in the words.",
    category: "poetry" as const,
    price: "12.99",
    stock: 40,
    coverImage: "/book-covers/book24.jpg",
    isbn: "978-0-123456-80-4",
    publisher: "Verse Press",
    publishedYear: 2024,
    pages: 128,
    isFeatured: false,
    isBestseller: false,
    rating: "4.4",
    reviewCount: 43,
  },
];

async function seed() {
  const db = getDb();

  console.log("Seeding books...");

  // Clear existing books
  await db.delete(books);

  // Insert sample books
  for (const book of sampleBooks) {
    await db.insert(books).values(book);
  }

  console.log(`Seeded ${sampleBooks.length} books successfully!`);
}

seed().catch(console.error);
